### ISSUE TITLE
Multiple sounds played when notification received

### ISSUE THREAD

**Issue by Mihir14** [peterhajas/MobileNotifier#12]
Hi,
Im using Prowl on my iPhone to receive notifications from Growl on my computer.
When a notification is received I notice that Tri Tone is played over my default sound setting for Prowl.
Is this a settings issue that I have overlooked?
Thanks,
Mihir

**Comment by peterhajas** [comment]
This is currently an issue being investigated - I'll leave this open until it's resolved.

**Comment by dcramps** [comment]
The issue seems to be here: https://github.com/peterhajas/MobileNotifier/blob/master/MNWhistleBlowerController.m

I don't think calling AudioServicesPlaySystemSound is necessary. I get the Tri-Tone sound as well as the app's custom sound playing while using MobileNotifier. Also, it vibrates twice if I have my volume switch turned on.

**Comment by sNick86** [comment]
Same issue here and normally at all Users. :)
But this tweak all in all is very very good. Love it!

**Comment by dfishburn** [comment]
Yes, in fact (several people including myself) would prefer both the default sound for the app and the MN sound to be heard.  That way I know whether to pull the phone out and look at it if I hear an SMS sound vs a Calendar sound.

**Comment by Kingfish** [comment]
Then perhaps there should be a setting to disable the MN sound since I too am getting both sounds at once and I find this annoying.  Simply hearing the default sound for the app causing the notification should be enough to let me know what app is alerting me.

Other than that, this is a great add-on that blows Apple's stock notification out of the water!  Thank you!

**Comment by Override79** [comment]
I agree with that, I am using MyProfiles application to change and disabled sound based on time, but right now I have no way to disable MN sound. Right now I am hearing 2 seperate sounds and 2 vibrations with some delay.

**Comment by VjyedSC0UFMc8z** [comment]
I also find the double sounds unnecessary. Great app though!

**Comment by doccoder212** [comment]
I'm having both of these problems as well. I had the first problem with mail enhancer (can anyone else suggest a better app to push inbuilt mail as notifications - including exchcange?) thus giving me the mail received sound followed by the MN sound. The second - almost the same, but I had errors with Auto Silent and iSilent as opposed to MyProfiles.

Quote:
Kingfish March 02, 2011 | link

Then perhaps there should be a setting to disable the MN sound since I too am getting both sounds at once and I find this annoying. Simply hearing the default sound for the app causing the notification should be enough to let me know what app is alerting me.

Other than that, this is a great add-on that blows Apple's stock notification out of the water! Thank you!
Override79 March 02, 2011 | link

I agree with that, I am using MyProfiles application to change and disabled sound based on time, but right now I have no way to disable MN sound. Right now I am hearing 2 seperate sounds and 2 vibrations with some delay.

**Comment by Gidgidonihah** [comment]
Ditto. I believe MN should just respect the sound of whatever notification. I don't know why you would need the tri-tone to tell you it's MN doing the notification. Allows for much more customization (or setting everything to tri-tone if you want) that way.

**Comment by peterhajas** [comment]
I am looking into this issue - don't think I've forgotten it! It's a problem I'm determined to fix.

I'm going to look into the MNWhistleBlowerController and see if I can make it happen.

**Comment by pmdarrow** [comment]
Peter, here's a reproducible test case if you need one:
1. Download the app "LiveProfile" on two iOS devices.
2. Create accounts on each of the devices and add one as a friend.
3. On device A, close LiveProfile, kill its process and lock the phone. Ensure the mute switch is off.
4. On device B, open LiveProfile and send a message to device A.

You'll hear the two sounds on device A, one tri-tone and one pop.

**Comment by peterhajas** [comment]
This has been fixed - https://github.com/peterhajas/MobileNotifier/issues/72 - thanks for reporting it!

**Comment by Kingfish** [comment]
Thanks Peter.  This was the deal breaker that kept me from re-installing.  Now that it's fixed, I can install again and try this great tweak out.  Keep those updates and improvements coming!
