### ISSUE TITLE
Intelligent Alert Dismiss

### ISSUE THREAD

**Issue by r0hit** [peterhajas/MobileNotifier#131]
Though I loved the feature, I still think it can be tweaked up a bit. The notifications should be deleted even when I directly open the app (and not by clicking on the Alert Dash). It's a bit annoying to see a notification when in fact I have already viewed it.

Apart from that, great work on the notification system. Easily one of the best jailbreak tweaks available on Cydia.

**Comment by peterhajas** [comment]
Thanks for your kind words! I will implement this feature.

Something I've been torn about - should this happen for all notifications, or just Push/Phone ones (not SMS)?

**Comment by r0hit** [comment]
I think it should be done for all notifications (including SMS); makes more sense. :)

**Comment by peterhajas** [comment]
This is an interesting opinion, I started to think the other way - I don't know if people would prefer to hang on to older notifications from Messages because they might only want to deal with one conversation at a time.

Is this a realistic concern, or am I jaded?

Thanks for your comments!

**Comment by r0hit** [comment]
Your point is valid but then people like me would usually use apps like Whatsapp for longer conversation. Also, if I receive, say, 25 messages in a day, then probably 15 might belong to one conversation and other 10 from random people - then those 10 messages will clog up my alert dash.

I think you should handle SMSes too in the next tweak as anyway we'll receive the notification - whether part of old thread or not. I hope I got the idea across.

**Comment by pocketlim** [comment]
I think this would make sense if there was a way for MobileNotifier to detect which items were viewed and cleared from the app itself. Let's take an example, Meebo, for a messaging app. Let's say I get 8 messages, 4 from person A and 4 from person B, so Meebo has an (8) on it (8 missed messages)

If I open Meebo and go to Person B's conversation, Meebo will clear out 4 messages (I honestly don't know if it clears out only 4 at this point, but just bear with the example) and then I hit the Home button. Meebo still shows 4, since it cleared out those 4 from person B. 

If there was a way for Mobile Notifier to detect the specific 4 messages cleared out and clear them from the Dashboard/Notification tray on its own, then I'm all for it.

If this is not possbile (I am not an iOS dev, so I don't know if it is!) then.... oh well!

**Comment by peterhajas** [comment]
Implemented! It'll be rolled out soon :)

**Comment by r0hit** [comment]
I hope you implemented it for SMS too? :)

**Comment by r0hit** [comment]
beta4r1 couldn't have been better.. keep up the awesome work!
