### ISSUE TITLE
Feature Request - Selective lockscreen slide to view

### ISSUE THREAD

**Issue by OneThatWalks** [peterhajas/MobileNotifier#183]
In the lockscreen view of mobile notifier, like apple and slide to view,  you should be able to open the mobile notifier alert queue and select an alert which will make the slide to unlock screen auto open that app.

**Comment by brb06** [comment]
Agreed. Also, is there any way that if the phone is locked and a notification comes in, that it shows up at the top like it does on the home screen when the phone is unlocked? Just because your phone is locked doesn't mean the notification should count as missed. 

All notifications should pile up on the lockscreen starting at the top of the screen (or below the clock for that matter) in order from newest to oldest. And then you should be able to slide to view like OneThatWalks mentioned.

**Comment by OneThatWalks** [comment]
I would also like to add some feauture requests.  Quick reply messaging for SMS and other messaging apps.
And what brb06 said,  about you aren't missing messages that just come in.

Have it show like under lockscreen in order:
(Current Notification) - similar to the look and feel of missed notifications
(Missed Notification) - like you have it
Then you can swipe to open current notification or select a different one from the list of missed.

Hope this made sense.

**Comment by btaroli** [comment]
As for the original post, see #175. You used to be able to tap-to-open in lock screen dash and slide to delete. The latter was causing issues, but in b4r1 they were both removed. I support re-adding the tap (or whatever gesture) to open apps from the lock screen, but for now I am using other apps (e.g. Notifier+) for this purpose.

**Comment by Kaizersoze** [comment]
To comply with the graphical interfaces of IOS, a tap on a lockscreen notification must start the application in connection with such notification (asking for lock code if used and must be checked) and a slide on a notification of lockscreen should bring up the button "DELETE" to remove the notification (but it's a security issu because someone can remove your missed call notifications).

**Comment by andheiberg** [comment]
Hi, I do agree with the fact that there needs to be a way of opening notifications from the lockscreen. Now that I have read Kaizersoze view on the matter I'm convinced that what he's describing is the best way of doing this. However I would like to add that I just saw a concept that shows off this kind of feature, though he has the same name as I, MobileNotifier is way better than his concept. Either way if you go to the 1:40 mark in his video you will see his take on this. His video can be found here http://vimeo.com/21208357 .

**Comment by timnovinger** [comment]
Please see [issue #45](https://github.com/peterhajas/MobileNotifier/issues/45), this feature will never be implemented as the lockscreen is a non-interactive element.
