### ISSUE TITLE
No lines on lockscreen view

### ISSUE THREAD

**Issue by JoeyP** [peterhajas/MobileNotifier#204]
Remove the lines that show underneath the notifications on the lock screen view, it would make it look much cleaner. Also, make the notifications on the lock screen tap-able to open up the application providing the notification.

**Comment by ghost** [comment]
Tap-able to open the app was good, but I'm not quite a fan of it.
It'd be great if it could be enabled/disabled.

**Comment by peterhajas** [comment]
For the lockscreen being an interactive element, it is not supposed to. It causes problems and issues with the device - it's meant to be unlocked.

For the lines on the lockscreen list view, can you give an argument either way? Why would it look cleaner?

**Comment by Kaizersoze** [comment]
In my opinion, the layout of the lockscreen list view is great but the notification list must be always displayed without tapping a button. 
I think Peter is right about the opportunity to tap on the lockscreen. For security the action on tap must be handled only after asking the unlock code IF USED AND MUST BE CHECKED.
A slide on a notification of lockscreen should bring up the button "DELETE" to remove the notification but it's a security issu because someone can remove your missed calls notifications.

**Comment by peterhajas** [comment]
The lines have been removed. Please submit additional issues if you would like to make feature requests. Thanks!
