### ISSUE TITLE
Cannot exit by tapping when in dashboard view

### ISSUE THREAD

**Issue by mergesort** [peterhajas/MobileNotifier#263]
In the old betas you were able to exit the dash when there were no notifications by tapping in the middle, much like you can do with the way Apple has it by default.  

I was hoping you could bring back that functionality since I don't see a particular reason for taking it out.

**Comment by Drudoo** [comment]
As we speak i am trying to fix this. It is a major problem =)

**Comment by btaroli** [comment]
I quite agree this is significant. Annoying enough in fact that I very nearly uninstalled it.

**Comment by Drudoo** [comment]
After using a few days on this problem, I can safely say that it is just as annoying trying to fix this as it is a problem =(
Since the dashboardview is a tableview you can press on it. I does not recognize touch events. I tried to add an invisible button on top of the view but that removed half of the header...

**Comment by timnovinger** [comment]
This issue was resolved in [this commit](https://github.com/peterhajas/MobileNotifier/commit/90582dee2603ac9c53b9b50ec0b0efd73d30da36).
