### ISSUE TITLE
Quickreply/quickcompose

### ISSUE THREAD

**Issue by Nateilage** [peterhajas/MobileNotifier#283]
I don't know how complicated it would be to add quick compose, but if you did that I would completely eleminate biteSMS... 

Also, there is no quickreply in the lockscreen. That would also be a great help.

Those are really only my two complaints... Otherwise I absolutely love mobilenotifier.

**Comment by timnovinger** [comment]
quickReply makes a ton of sense because the user is responding to a given SMS notification. MobileNotifier's goal is to rework the notification system, not provide a quick way to _create_ an SMS message.

As far as lockscreen behavior goes, sorry but the lockscreen is not a user interactive element of the phone and as far as MobileNotifier is concerned, it never will be. It's meant for displaying information only. 

## 

## Tim Novinger

Twitter:  @timnovinger
Skype: tim.novinger
Mobile: 260.918.4937

## Web:  timnovinger.com

Sent with Sparrow (http://www.sparrowmailapp.com)
