### ISSUE TITLE
Sound, mail, missed calls

### ISSUE THREAD

**Issue by to70no** [peterhajas/MobileNotifier#286]
I uninstalled Lockinfo to give Mobilenotifier a fair chance. Will it support missed call and email notifications anytime soon? Also, why does it always play tritone for incoming sms regardless of my selection in sound settings? These are all very basic functions handled by Lockinfo. Am i missing something?

**Comment by timnovinger** [comment]
At the moment MobileNotifier only handles push notifications, sms/mms, calendar invites, and voicemail alerts. Further support _might_ come, but as of right now it's not planned.

The sound issues you reported have been fixed in later dev builds. Please be patient and wait for a new version to hit Cydia.
