### ISSUE TITLE
Google Calendar Popups not picked up

### ISSUE THREAD

**Issue by dfishburn** [peterhajas/MobileNotifier#46]
I sync my Google calendars (which are setup as ActiveSync accounts for push).
When I create a new calendar entry I add an alarm as a Popup (in the Google web page).
When these alarms go off, MobileNotifier does not notice these, and therefore does not add them to the list of notifications.

**Comment by ahti** [comment]
what do you mean by MobileNotifier does not notice them?
on my setup (basically the same) the iphone shows the alarm in a popup bublle, like without mobilenotifier. I also woould preferr this behaviour over having mobilenotifier pick up those kind of events as well, because calendar alerts you really dont wanna miss and with mobile notifier, they tend to become only visible in the dashboard

**Comment by dfishburn** [comment]
Yes, MN does not add these calendar alerts to its list.
Though we had been discussing on other threads having the ability to choose which apps should and should not be picked up by MN.  If that is implemented, it would address your issue.
