### ISSUE TITLE
Notifications stay when in text messages

### ISSUE THREAD

**Issue by arsenm** [peterhajas/MobileNotifier#5]
If I have a notification from person X, and I launch messages, thus viewing the messages, the notification remains about the text message.

**Comment by Skelsey** [comment]
If you double tap the home button (open multitasking window) you can select the previous notifications and remove them :) temporary solution :)

**Comment by Jonyjack** [comment]
When I double tap on a iPod Touch 2G MC, nothing appears. Is it normal? iTouch 2G MC don't have multitasking?

**Comment by Skelsey** [comment]
I don't think it has multitasking

**Comment by Jonyjack** [comment]
... So I can't remove notifications on my lockscreen... What's why I'm waiting for a toggle to deactivate it ;)

Thanks

**Comment by peterhajas** [comment]
Jonyjack, please look into your Activator settings. Your device is supported.

**Comment by Jonyjack** [comment]
Yes, thank you I can clear notifications that's great.
Unfortunately, my iPod does not have multitasking anyway :/ but it's not the topic, thank you again ;)

**Comment by ahti** [comment]
of topic: Jonyjack you can indeed activate multitasking, hat it on my ol iPhone 3g for a long time, google will help.
btt: maybe you should bring up the alert dashboard on devices not supporting multitasking either way for a uniform interface?

**Comment by Jonyjack** [comment]
Wow thanks Ahti it works very well :)

**Comment by swemoney** [comment]
I, personally, would also love to see this added. Just for things that MobileNotifier can tell where you launched into an application. Messages would be great because you should be able to clear all messages from the recipient you've just viewed. But not sure if this would work in all applications that you might want to keep multiple notifications around before launching the applications kills them all automatically. I just think care has to be taken to not treat all applications the same when auto-removing things from the dashboard.
